### PR TITLE
Remove name argument to _restore

### LINKED ISSUE #3501: Can't restore folders from a backup in Supervisor 2022.03.2
### Describe the issue you are experiencing

Restoring folders from a backup doesn't work in Supervisor 2022.03.2. This apply to local, media, ssl and share folders

### What is the used version of the Supervisor?

2022.03.2

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Debian

### What is the version of your installed operating system?

Debian Bullseye (aarch64)

### What version of Home Assistant Core is installed?

2022.3.3

### Steps to reproduce the issue

1.
2.
3.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
22-03-10 10:14:41 INFO (MainThread) [supervisor.backups.manager] Partial-Restore 9d7708fc start
22-03-10 10:14:47 INFO (MainThread) [supervisor.backups.manager] Restoring 9d7708fc Docker config
22-03-10 10:14:47 INFO (MainThread) [supervisor.backups.manager] Restoring 9d7708fc folders
22-03-10 10:14:47 WARNING (MainThread) [supervisor.backups.backup] Can't restore folder addons/local: _restore() takes 0 positional arguments but 1 was given
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by ludeeus**
## Proposed change

Fixes #3501

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (which adds functionality to the supervisor)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue:
- Link to documentation pull request:
- Link to cli pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] Local tests pass. **Your PR cannot be merged unless tests pass**
- [ ] There is no commented out code in this PR.
- [ ] I have followed the [development checklist][dev-checklist]
- [ ] The code has been formatted using Black (`black --fast supervisor tests`)
- [ ] Tests have been added to verify that the new code works.

If API endpoints of add-on configuration are added/changed:

- [ ] Documentation added/updated for [developers.home-assistant.io][docs-repository]

[dev-checklist]: https://developers.home-assistant.io/docs/en/development_checklist.html
[docs-repository]: https://github.com/home-assistant/developers.home-assistant

### CODE REVIEW

**Comment by johnlento** [comment]
Any idea when this one will be released? I’m sort of dead in the water trying to get HA backup and running and just trying to gauge when this will be good to go.

**Review by mdegat01 — APPROVED** [review]

**Comment by belimawr** [comment]
> Any idea when this one will be released? I’m sort of dead in the water trying to get HA backup and running and just trying to gauge when this will be good to go.

If you're having problems with the add-ons, there is a workaround on this comment: https://github.com/home-assistant/supervisor/issues/3497#issuecomment-1063791492

I've just migrated my HA from a RPi to a VM and it worked like a charm. Here is what I did:
1. Full backup on RPi
2. Shutdown the Pi
3. Start a VM
4. Go through the on-boarding very quickly, so I can get to the dashboard
5. Set the static IP address to the same the RPi was using
6. Install all Add-Ons I had
7. Restore the backup.

After that everything was working like before.

**Comment by johnlento** [comment]
Honestly re-adding the add ons got me far but none of the actual data files seem to restore either. All 100+ zigbee and zwave devices aren’t there, users, are broken, etc. Addon’s proper seem to be OK but everything else is broken.

**Comment by chrisuk-web** [comment]
> Honestly re-adding the add ons got me far but none of the actual data files seem to restore either. All 100+ zigbee and zwave devices aren’t there, users, are broken, etc. Addon’s proper seem to be OK but everything else is broken.

I think I have the same issue after having tried to do a restore. Error message I am seeing from supervisor is: Error: ‘Supervisor.restart’ blocked from execution, system is not running - CoreState.STARTUP

I cannot start HA. @johnlento is this what you have?

**Pull request merged**
