### PR TITLE
Update to python 3.11

### PR DESCRIPTION
**Pull request by mdegat01**
## Proposed change

Update supervisor to python 3.11. Will try and bump the version of alpine in a separate PR.

All tests are passing after fixing places we were calling `asyncio.wait` with coroutines. This definitely could use some testing on a live system though. Will do it on mine, would appreciate anyone else trying that wants to.

## Type of change

- [x] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (which adds functionality to the supervisor)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue:
- Link to documentation pull request:
- Link to cli pull request:

## Checklist

- [x] The code change is tested and works locally.
- [x] Local tests pass. **Your PR cannot be merged unless tests pass**
- [x] There is no commented out code in this PR.
- [x] I have followed the [development checklist][dev-checklist]
- [x] The code has been formatted using Black (`black --fast supervisor tests`)
- [x] Tests have been added to verify that the new code works.

If API endpoints of add-on configuration are added/changed:

- [ ] Documentation added/updated for [developers.home-assistant.io][docs-repository]

[dev-checklist]: https://developers.home-assistant.io/docs/en/development_checklist.html
[docs-repository]: https://github.com/home-assistant/developers.home-assistant

### CODE REVIEW

**Comment by frenck** [comment]
I've pulled it locally, but wasn't able to build and run the image from this PR.

CleanShot 2023-05-17 at 00 09 32

The `cchardet` package is not working/compatible with Python 3.11. For core, we have switched to the `faust-cchardet` package a few releases back (drop-in replacement, currently pinned to 2.1.18).

**Comment by mdegat01** [comment]
@frenck ok looks like there were a few more things to fix. But I think I got them all now and am able to build an image from this branch and run it on my machine successfully. Can you give it a shot too? Assuming it works for you as well I think we can merge.

**Review by frenck — APPROVED** [review]
Initial testing on my end looked great.

I haven't been able to test everything just of yet, but the initial testing showed at least the critical parts are working.

../Frenck

**Review by frenck — CHANGES_REQUESTED** [review]
Came across this one:

```
23-05-21 20:40:40 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/api/middleware/security.py", line 185, in block_bad_requests
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/api/middleware/security.py", line 201, in system_validation
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/api/middleware/security.py", line 220, in token_validation
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/api/middleware/security.py", line 280, in core_proxy
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/api/ingress.py", line 105, in handler
    return await self._handle_websocket(request, addon, path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/api/ingress.py", line 149, in _handle_websocket
    await asyncio.wait(
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 415, in wait
    raise TypeError("Passing coroutines is forbidden, use tasks explicitly.")
TypeError: Passing coroutines is forbidden, use tasks explicitly.
```

And

```
/usr/local/lib/python3.11/ipaddress.py:1205: RuntimeWarning: coroutine '_websocket_forward' was never awaited
Coroutine created at (most recent call last)
  File "/usr/local/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/supervisor/supervisor/api/middleware/security.py", line 185, in block_bad_requests
    return await handler(request)
  File "/usr/src/supervisor/supervisor/api/middleware/security.py", line 201, in system_validation
    return await handler(request)
  File "/usr/src/supervisor/supervisor/api/middleware/security.py", line 220, in token_validation
    return await handler(request)
  File "/usr/src/supervisor/supervisor/api/middleware/security.py", line 280, in core_proxy
    return await handler(request)
  File "/usr/src/supervisor/supervisor/api/ingress.py", line 105, in handler
    return await self._handle_websocket(request, addon, path)
  File "/usr/src/supervisor/supervisor/api/ingress.py", line 151, in _handle_websocket
    _websocket_forward(ws_server, ws_client),
  return int.from_bytes(map(cls._parse_octet, octets), 'big')
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```

This is produced by installing the Node-RED add-on, which communicates over the WebSocket proxy the Supervisor provides.

**Comment by mdegat01** [comment]
Thanks @frenck ! Looks like I missed an `asyncio.wait` call in ingress, both of those seem to come from the same place. Fixed it

**Review by frenck — APPROVED** [review]
Works and looks great @mdegat01 👍 

../Frenck

**Pull request merged**
