### PR TITLE
Add Support for NetworkManager managed bridge interfaces.

### PR DESCRIPTION
**Pull request by xonestonex**
## Proposed change

https://github.com/home-assistant/operating-system/pull/2304 added support for managed bridge interfaces in Home Assistant Operating System. It allows for example the realization of a simple WiFi-ethernet bridge within a custom add-in.
This PR allows the supervisor to handle such bridge interfaces and is needed for other add-ins like the Samba add-in to see the bridge interfaces.

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (which adds functionality to the supervisor)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue:
- Link to documentation pull request:
- Link to cli pull request:

## Checklist

- [X] The code change is tested and works locally.
- [ ] Local tests pass. **Your PR cannot be merged unless tests pass**
- [X] There is no commented out code in this PR.
- [X] I have followed the [development checklist][dev-checklist]
- [X] The code has been formatted using Black (`black --fast supervisor tests`)
- [ ] Tests have been added to verify that the new code works.

If API endpoints of add-on configuration are added/changed:

- [ ] Documentation added/updated for [developers.home-assistant.io][docs-repository]

[dev-checklist]: https://developers.home-assistant.io/docs/en/development_checklist.html
[docs-repository]: https://github.com/home-assistant/developers.home-assistant

### CODE REVIEW

**Comment by mdegat01** [comment]
Your addon makes an unmanaged interface:
https://github.com/mattlongman/Hassio-Access-Point/blob/5db13bd60d2f8c7da4d4575558b7f1e6d5d8ef33/hassio-access-point/run.sh#L62

Supervisor ignores those, your PR doesn't change that. You added `BRIDGE` to the first part of this if statement but the interface your addon is adding is still going to be skipped for being unmanaged by the second part:
https://github.com/home-assistant/supervisor/blob/63499f0a1a2868038241f7625d8785caae502fcc/supervisor/dbus/network/__init__.py#L204-L213

For this to be merged there needs to be test cases showing how you expect supervisor to work with bridge interfaces and confirming that use case is functional.

**Review by mdegat01 — CHANGES_REQUESTED** [review]
Your addon makes an unmanaged interface:
https://github.com/mattlongman/Hassio-Access-Point/blob/5db13bd60d2f8c7da4d4575558b7f1e6d5d8ef33/hassio-access-point/run.sh#L62

Supervisor ignores those, your PR doesn't change that. You added `BRIDGE` to the first part of this if statement but the interface your addon is adding is still going to be skipped for being unmanaged by the second part:
https://github.com/home-assistant/supervisor/blob/63499f0a1a2868038241f7625d8785caae502fcc/supervisor/dbus/network/__init__.py#L204-L213

For this to be merged there needs to be test cases showing how you expect supervisor to work with bridge interfaces and confirming that use case is functional.

Or at the very least detail out explicitly the test cases you would like to make and I can help you make them. I know supervisor's use of dbus in testing is a bit complicated.

**Comment by pvizeli** [comment]
If we handle the bridge, it also needs code and CLI to work with it.

**Comment by xonestonex** [comment]
> Your addon makes an unmanaged interface: https://github.com/mattlongman/Hassio-Access-Point/blob/5db13bd60d2f8c7da4d4575558b7f1e6d5d8ef33/hassio-access-point/run.sh#L62
> 
> Supervisor ignores those, your PR doesn't change that. You added `BRIDGE` to the first part of this if statement but the interface your addon is adding is still going to be skipped for being unmanaged by the second part:
> 
This isn't my addon. Its also doesn't create a bridge. It creates a separate network on the wifi interface. This network is not seen by Home Assistant and this results in problems. For example the shelly integration doesn't detect devices connected to the wifi network. 
So I've started a proper implementation, that uses the NetworkManager and allows to create a full network bridge. https://github.com/home-assistant/operating-system/pull/2304 enables NetworkManager to manage bridge interfaces and to create access points on the wifi interface directly in network manager without hostapd.

> https://github.com/home-assistant/supervisor/blob/63499f0a1a2868038241f7625d8785caae502fcc/supervisor/dbus/network/__init__.py#L204-L213
> 
> For this to be merged there needs to be test cases showing how you expect supervisor to work with bridge interfaces and confirming that use case is functional.
> 
> Or at the very least detail out explicitly the test cases you would like to make and I can help you make them. I know supervisor's use of dbus in testing is a bit complicated.

I have no clue how to create tests for it, but the following commands create such a bridge interface and attach the ethernet and wifi interface to.
```
nmcli connection add con-name 'Test Bridge' ifname br0 type bridge ipv4.method auto ipv6.method disabled connection.autoconnect yes stp no
nmcli connection add con-name 'Test Ethernet' ifname eth0 type bridge-slave master 'Test Bridge' connection.autoconnect yes
nmcli connection add con-name 'Test Hotspot' ifname wlan0 type wifi slave-type bridge master 'Test Bridge' wifi.band bg wifi.channel 6 wifi.mode ap wifi.ssid TestHotspot wifi-sec.key-mgmt wpa-psk wifi-sec.psk secretKey
iptables -A FORWARD -p all -i br0 -j ACCEPT
```
Without the above patch, the bridge interface is not seen by the supervisor and the wlan0 and eth0 interface don't have a IP address.  Addons that use the supervisor network information's don't work correctly, like the samba addon.

**Comment by xonestonex** [comment]
> 



> If we handle the bridge, it also needs code and CLI to work with it. I guess it could be similarly implemented as vlan support

Can you point me to the code for the vlan implementation, because i have no idea what kind of support you want in the CLI. The nmcli already allows all the configuration and the "GUI-part" would be in the configuration of a new addin, that executes the right nmcli commands.

**Comment by agners** [comment]
> Addons that use the supervisor network information's don't work correctly, like the samba addon.

Presumably this is just because the Samba add-on doesn't bind to that interface read interface information from Supervisor in https://github.com/home-assistant/addons/blob/ce10622/samba/rootfs/etc/cont-init.d/samba.sh#L23-L30.

> Can you point me to the code for the vlan implementation, because i have no idea what kind of support you want in the CLI.

Accessing the NetworkManager D-Bus API is side-stepping the Supervisor's control over networking. To make it an useful network feature, we should implement HA CLI support to create network bridges.

Today, the HA CLI allwos to create VLAN's see https://github.com/home-assistant/cli/blob/304aef1/cmd/network_vlan.go#L13. 


One think I wonder is how does the enabled bridge support in NetworkManager affect the system today? What happens if you create a bridge without this merged? Is there a breakage of current functionality?

**Comment by xonestonex** [comment]
> Today, the HA CLI allwos to create VLAN's see https://github.com/home-assistant/cli/blob/304aef1/cmd/network_vlan.go#L13.

Maybe i will find some time in march to add support for bridge interfaces to the HA CLI.
 
> One think I wonder is how does the enabled bridge support in NetworkManager affect the system today? What happens if you create a bridge without this merged? Is there a breakage of current functionality?

I haven't tested it much, but the regular integrations seam to work but the Samba addin didn't start. Also the "Network Adapter" part in the Network GUI didn't show a detected IP. I assume, that everything that uses this information will also break. I've also tried to create a bridge without NetworkManager with brctl. But in this case HomeAssistant had errors about not being online.

**Pull request closed without merging**
