### PR TITLE
Add support for NET_BIND_SERVICE privileges

### PR DESCRIPTION
**Pull request by mrueg**
## Proposed change
Add support for CAP_NET_BIND_SERVICE, which allows to bind a socket to Internet domain privileged ports (port	numbers less than 1024). This will help reducing the exposed capabilities for services that run as addons in home assistant.

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (which adds functionality to the supervisor)
- [x] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue:
- Link to documentation pull request:
- Link to cli pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] Local tests pass. **Your PR cannot be merged unless tests pass**
- [x] There is no commented out code in this PR.
- [ ] I have followed the [development checklist][dev-checklist]
- [x] The code has been formatted using Ruff (`ruff format supervisor tests`)
- [ ] Tests have been added to verify that the new code works.

If API endpoints of add-on configuration are added/changed:

- [ ] Documentation added/updated for [developers.home-assistant.io][docs-repository]

[dev-checklist]: https://developers.home-assistant.io/docs/en/development_checklist.html
[docs-repository]: https://github.com/home-assistant/developers.home-assistant

## Summary by CodeRabbit

- **New Features**
  - Enhanced security rating for add-ons by incorporating the `NET_BIND_SERVICE` capability.

### CODE REVIEW

**Comment by mdegat01** [comment]
@mrueg can you provide an example of when and why someone would need to list this capability? Because we currently have lots of addons doing this without requesting any special permissions.

For example, from official addons we have the [nginx proxy](https://github.com/home-assistant/addons/blob/master/nginx_proxy/config.yaml) and [Let's Encrypt](https://github.com/home-assistant/addons/blob/master/letsencrypt/config.yaml) addons which both bind to 80 by default. Or [Nginx Proxy manager](https://github.com/hassio-addons/addon-nginx-proxy-manager/blob/main/proxy-manager/config.yaml) which binds to 80, 81 and 443 by default from the community add-ons. Or [Adguard Home](https://github.com/hassio-addons/addon-adguard-home/blob/main/adguard/config.yaml) which runs on the host network and binds to 80 and 53 by default from community add-ons as well.

To my knowledge all of these addons are working fine and not running into security issues requiring permissions to bind to these ports. So when would an addon dev need to request this capability? What is different from these?

**Comment by agners** [comment]
Hm, I was wondering why binding to these ports without capabilities actually works. To my knowledge, at least when host network is at play, even when running as root, when the capability is missing a process should not be able to bind to ports lower than 1024.

However, from this [Medium post](https://medium.com/@olivier.gaumond/why-am-i-able-to-bind-a-privileged-port-in-my-container-without-the-net-bind-service-capability-60972a4d5496), the reason for that seems to be that Docker actually reconfigures what is considered privileged ports, and hence allow even without the capability.

So to me it seems that this capability is really unnecessary when Docker is used :man_shrugging:

**Comment by agners** [comment]
Closing as this seems unnecessary to me. Feel free to comment/ping me if you feel this is not warranted.

**Comment by mrueg** [comment]
Apologies for the late response and thanks for checking! You're right, I wasn't aware that docker sets this sysctl value, so it doesn't provide any benefit to add this privilege.

Apologies again for the noise, I was under the impression it could help folks to run with more limited capabilities.

**Comment by agners** [comment]
No worries, thanks for the update/confirmation!

**Pull request closed without merging**
