### PR TITLE
Fix mount Issue #2590

### PR DESCRIPTION
**Pull request by adamoutler**
The /dev should not be mounted as RO under all circumstances. This breaks a lot of features  https://github.com/home-assistant/supervisor/issues/2590

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (which adds functionality to the supervisor)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] Local tests pass. **Your PR cannot be merged unless tests pass**
- [ ] There is no commented out code in this PR.
- [ ] I have followed the [development checklist][dev-checklist]
- [ ] The code has been formatted using Black (`black --fast supervisor tests`)
- [ ] Tests have been added to verify that the new code works.

If API endpoints of add-on configuration are added/changed:

- [ ] Documentation added/updated for [developers.home-assistant.io][docs-repository]

[dev-checklist]: https://developers.home-assistant.io/docs/en/development_checklist.html
[docs-repository]: https://github.com/home-assistant/developers.home-assistant

### CODE REVIEW

**Comment by adamoutler** [comment]
There are three valid reasons to reenable mounting dev as RW:

1. I2C is required for active cooling on the most popular Raspberry Pi Case and is not practical by any other means on Home Assistant Operating System
2. Serial is required for active cooling and front USB ports on DeskPi Pro and is not practical by any other means on Home Assistant Operating System.
3. Debug Port 22222 enablement, on either of the above cases, on Home Assistant Operating System is not practical By any other means.

When I speak of practical, I am speaking from an end user perspective, whereby the solution would involve

2. Physical access to the machine, rebooted, with keyboard and monitor attached.
2. Logging in to both the Home Assistant CLI, then the terminal.
3. Typing long strings of characters copied by hand from another computer or phone, by the user, via keyboard.
4.  A good understanding of Linux and Home Assistant Operating System because these workarounds are not documented.

**Comment by frenck** [comment]
- For I2C we can build handling, it is not needed to provide full dev write access for that.
- For Serial and USB access, we already have handled and handing out write access for that is not needed.

> Debug Port 22222 enablement, on either of the above cases, on Home Assistant Operating System is not practical By any other means.

Not sure how that is even remotely related to handing out RW access to /dev. If an add-on needs access to devices, the devices option can be used. Alternatively, there are other options available to gain access to e.g., gpio, uart and raw USB ports.

In the linked issue, there are a few different things going on, that do not have the same origins or resolutions.  While this might solve it globally, just opening up this in full, is irresponsible and risky from a security perspective.

**Comment by adamoutler** [comment]
> In the linked issue, there are a few different things going on, that do not have the same origins or resolutions. While this might solve it globally, just opening up this in full, is irresponsible and risky from a security perspective.

I understand security is important. My job is security. 
I'd love to increase it everywhere, but security is only 1/2 of the usability/security paradigm.  The most secure system is powered off, sealed in concrete, and at the bottom of the ocean, but that's not usable.   

This change broke a lot of documentation, use cases, and add-ons.  All the problems come from this recent change of mounting the /dev as RO.    It was irresponsible to make the change without warning. It was irresponsible to not document workarounds.  It was irresponsible to not mention it in the release.  

The responsible thing is to revert this change until the workarounds are established.   These use cases are important to users.

**Comment by frenck** [comment]
>  It was irresponsible to make the change without warning. It was irresponsible to not document workarounds. It was irresponsible to not mention it in the release.

That is a different discussion, but that is no circumstance a good reason to implement the suggestion in this PR.

**Comment by adamoutler** [comment]
> That is a different discussion, but that is no circumstance a good reason to implement the suggestion in this PR.

Mounting as RO is a tradeoff on security, not a straight up improvement.  
This does not improve security for the systems which are overheating.  You can argue that removing USB access from the front ports increases security.  Removing the ability to debug will increase security, but also make it more difficult to audit the security.

**Comment by frenck** [comment]
> This does not improve security for the systems which are overheating. 

? I feel like that is a loose statement.

My opinion is that this should not be merged, in any circumstance. I leave it up to a second reviewer to decide.

**Comment by adamoutler** [comment]
> > This does not improve security for the systems which are overheating.
> 
> ? I feel like that is a loose statement.

This change broke the methods used to enable active cooling on ArgonOne and DeskPi Pro.  It broke the front USB port on desk pi pro.  There is no way to make it work on these systems because there is no plugging the drive into a computer.  There are no workarounds.  There is no documentation on the changes.  There is no workaround.  These systems were doomed on new installation because of mounting as RO.

**Comment by frenck** [comment]
? Isn't that an OS issue instead? Sounds like this is being worked around from an add-on level?

**Comment by adamoutler** [comment]
> ? Isn't that an OS issue instead? Sounds like this is being worked around from an add-on level?

Yes.  Since the system is docker and there are expectations of docker running without protection, the OS can be configured from a container without requiring changes to the OS accounting for all individual user configurations.  This is a huge change for the project and shouldn't be slid into a point update, without workarounds, fixed, and documentation,

**Comment by frenck** [comment]
> Since the system is docker and there are expectations of docker running without protection

That is incorrect and has never been the case. The Home Assistant OS & Supervised installation types are not here to be "just Docker". If you are looking for that level of control, you should use Home Assistant Container.

**Comment by adamoutler** [comment]
> That said, you are trying to solve something, that should have been worked around on that level. Now the workaround stops working, mount point needs to change, with all sorts of impacts? That makes no sense in any way and strengthens the reasoning to not merge this.

I am not saying that this change should not be made. It should be.  But disregarding current use cases to make undocumented changes to the undocumented security model is shady and underhanded.  This change is not ready yet.

If I migrate the functionality of the add-ons I maintain into the supervisor would they be accepted?  I imagine  this would take some research, discussion, and some prototyping of what is desirable within HA CLI since there are no existing examples of `raspi-config`-like functionality within the HA CLI. 

In the mean time reverting this change would provide users with a bridged to continue installing Home Assistant Operating System.

**Comment by bsp9493** [comment]
I apologize in advance as this conversation is WAY above me.

At this time, all I am trying to do is install/activate i2c in order to access the fan on my argon 40 case.
  
> I2C is required for active cooling on the most popular Raspberry Pi Case and is not practical by any other means on Home Assistant Operating System

in the interim, can someone please point me to the “impractical” solution to installing i2c ?

As always, I appreciate the work you guys do and any help you can provide.

**Comment by frenck** [comment]
@bsp9493 That is not really related to this PR. If you are in need of support, please use our Community Forums or Discord chat.

As for you question, that is documented here: <https://www.home-assistant.io/common-tasks/os#enable-i2c>

**Comment by adamoutler** [comment]
> As for your question, that is documented here: https://www.home-assistant.io/common-tasks/os#enable-i2c

You're asking a user manually and precisely type lines of bash code into a terminal via keyboard.   When I wrote that document, my intent was to use the SSH and Web Terminal  App, but I documented it as a feature of the Home Assistant CLI because it technically is and could be useful in an emergency.

**Comment by frenck** [comment]
This is completely off-topic. Lets discuss that somewhere else. I agree on that it could be easier, I'm sure we'd happy to accept any pull requests to both the Supervisor & Frontend repositories to make that happen.

**Comment by adamoutler** [comment]
> This is completely off-topic. 
IMO, everything here is on-topic.  It's the fallout from the changes and continuation of the last pull request which caused the problems. If you're truly opposed to this change after seeing this entire conversation, I will close the topic.  But I think 2021.3 could benefit from it until a proper solution is created elsewhere.

**Comment by frenck** [comment]
> If you're truly opposed to this change after seeing this entire conversation

I think I've made that clear already a couple of times. I've also stated I left it up to another reviewer to decide.

**Pull request closed without merging**
