### PR TITLE
Abort create snapshot on failure

### LINKED ISSUE #2391: Missing files and folders in snapshot
### Describe the issue

Im running automatic snapshots every night, and now i tried a manual snapshot to.
Everything seems to be fine untill i tried to restore the snapshot.
It's missing a couple of folders and files from the config folder.
And i guess it is because of the error in the supervisor log, that the snapshot somehow "finish" even if there is an error that makes the snapshot incomplete.
I have posted a topic in the community forum with more images to: [https://community.home-assistant.io/t/snapshot-missing-folders-and-files/259115](https://community.home-assistant.io/t/snapshot-missing-folders-and-files/259115)
### Steps to reproduce

1. ...Make a manual snapshot
2. ...Download and extract it on my desktop computer
3. ...The folders: “image”, “packages”, “python_scripts” and “www” are for sure missing, and about 18 files in the root of config folder seems to be missing.

### Enviroment details

- **Operating System:**:  Home Assistant OS 5.9
- **Supervisor version:**: 2020.12.7
- **Home Assistant version**: 2020.12.1

### Supervisor logs

<details>
<summary>Supervisor logs</summary>

```
20-12-29 15:58:43 INFO (MainThread) [supervisor.snapshots] Creating new full-snapshot with slug b064a5cf
20-12-29 15:58:43 INFO (MainThread) [supervisor.snapshots] Snapshotting b064a5cf store Add-ons
20-12-29 15:58:43 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on a0d7b954_ssh
20-12-29 15:58:43 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon a0d7b954_ssh
20-12-29 15:58:43 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on core_samba
20-12-29 15:58:43 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon core_samba
20-12-29 15:58:43 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on a0d7b954_vscode
20-12-29 15:58:49 INFO (MainThread) [supervisor.api.security] /supervisor/logs access from a0d7b954_ssh
20-12-29 15:58:54 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon a0d7b954_vscode
20-12-29 15:58:54 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on core_mosquitto
20-12-29 15:58:54 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon core_mosquitto
20-12-29 15:58:54 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on a0d7b954_phpmyadmin
20-12-29 15:58:54 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon a0d7b954_phpmyadmin
20-12-29 15:58:54 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on cebe7a76_hassio_google_drive_backup
20-12-29 15:58:54 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon cebe7a76_hassio_google_drive_backup
20-12-29 15:58:54 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on a0d7b954_grafana
20-12-29 15:58:54 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon a0d7b954_grafana
20-12-29 15:58:54 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on a0d7b954_influxdb
20-12-29 16:00:41 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon a0d7b954_influxdb
20-12-29 16:00:41 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on a0d7b954_adb
20-12-29 16:00:41 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon a0d7b954_adb
20-12-29 16:00:41 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on core_check_config
20-12-29 16:00:41 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon core_check_config
20-12-29 16:00:41 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on a0d7b954_sonweb
20-12-29 16:00:41 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon a0d7b954_sonweb
20-12-29 16:00:41 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on a0d7b954_nodered
20-12-29 16:00:41 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon a0d7b954_nodered
20-12-29 16:00:41 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on a0d7b954_logviewer
20-12-29 16:00:41 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon a0d7b954_logviewer
20-12-29 16:00:41 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on a0d7b954_grocy
20-12-29 16:00:41 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon a0d7b954_grocy
20-12-29 16:00:41 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on a0d7b954_portainer
20-12-29 16:00:41 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon a0d7b954_portainer
20-12-29 16:00:41 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on a0d7b954_glances
20-12-29 16:00:41 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon a0d7b954_glances
20-12-29 16:00:49 INFO (SyncWorker_3) [supervisor.docker.addon] Export image 15ef4d2f/amd64-addon-esphome-dev to /data/tmp/tmptpisd2l3/image.tar
20-12-29 16:00:52 INFO (SyncWorker_3) [supervisor.docker.addon] Export image 15ef4d2f/amd64-addon-esphome-dev done
20-12-29 16:00:52 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on 15ef4d2f_esphome-dev
20-12-29 16:03:53 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon 15ef4d2f_esphome-dev
20-12-29 16:03:53 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on 6a15710b_tasmobackup
20-12-29 16:03:53 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon 6a15710b_tasmobackup
20-12-29 16:03:53 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on core_mariadb
20-12-29 16:06:23 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon core_mariadb
20-12-29 16:06:23 INFO (MainThread) [supervisor.snapshots] Snapshotting b064a5cf store folders
20-12-29 16:06:23 INFO (SyncWorker_1) [supervisor.snapshots.snapshot] Snapshot folder ssl
20-12-29 16:06:23 INFO (SyncWorker_1) [supervisor.snapshots.snapshot] Snapshot folder ssl done
20-12-29 16:06:23 INFO (SyncWorker_4) [supervisor.snapshots.snapshot] Snapshot folder share
20-12-29 16:06:23 INFO (SyncWorker_4) [supervisor.snapshots.snapshot] Snapshot folder share done
20-12-29 16:06:23 INFO (SyncWorker_5) [supervisor.snapshots.snapshot] Snapshot folder media
20-12-29 16:06:24 INFO (SyncWorker_5) [supervisor.snapshots.snapshot] Snapshot folder media done
20-12-29 16:06:24 INFO (SyncWorker_0) [supervisor.snapshots.snapshot] Snapshot folder homeassistant
20-12-29 16:06:27 WARNING (SyncWorker_0) [supervisor.snapshots.snapshot] Can't snapshot folder homeassistant: [Errno 74] Bad message: '/data/homeassistant/.git/objects/99/be72fb13c0f14b8bfc501dcc6fe86dc8cd984b'
20-12-29 16:06:27 INFO (SyncWorker_7) [supervisor.snapshots.snapshot] Snapshot folder addons/local
20-12-29 16:06:27 INFO (SyncWorker_7) [supervisor.snapshots.snapshot] Snapshot folder addons/local done
20-12-29 16:06:28 INFO (MainThread) [supervisor.snapshots] Creating full-snapshot with slug b064a5cf completed
20-12-29 16:06:34 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup
20-12-29 16:06:34 INFO (MainThread) [supervisor.api.security] /snapshots/b064a5cf/info access from cebe7a76_hassio_google_drive_backup
20-12-29 16:06:35 INFO (MainThread) [supervisor.api.security] /snapshots/b064a5cf/download access from cebe7a76_hassio_google_drive_backup
20-12-29 16:06:35 INFO (MainThread) [supervisor.api.snapshots] Downloading snapshot b064a5cf

```

</details>

### System Information

<details>
<summary>System Information</summary>

```
arch: amd64
channel: stable
docker: 19.03.13
features:
- reboot
- shutdown
- services
- network
- hostname
- hassos
hassos: "5.9"
homeassistant: 2020.12.1
hostname: HassOS
logging: info
machine: qemux86-64
operating_system: Home Assistant OS 5.9
supervisor: 2020.12.7
supported: true
supported_arch:
- amd64
- i386
timezone: Europe/Stockholm
```

</details>

### PR DESCRIPTION
**Pull request by ludeeus**
## Proposed change

When snapshot create fails, abort and cleanup so the user does not end up with a broken snapshot.

#FailFastFailHard

```log
21-02-08 10:20:45 DEBUG (MainThread) [supervisor.api.security] /snapshots/new/full access from Home Assistant
21-02-08 10:20:45 INFO (MainThread) [supervisor.snapshots] Creating new full-snapshot with slug d3cc4b1b
21-02-08 10:20:45 INFO (MainThread) [supervisor.snapshots] Snapshotting d3cc4b1b store Add-ons
21-02-08 10:20:45 INFO (MainThread) [supervisor.snapshots] Snapshotting d3cc4b1b store folders
21-02-08 10:20:45 INFO (SyncWorker_2) [supervisor.snapshots.snapshot] Snapshot folder share
21-02-08 10:20:45 INFO (SyncWorker_2) [supervisor.snapshots.snapshot] Snapshot folder share done
21-02-08 10:20:45 ERROR (MainThread) [supervisor.snapshots] Can't save folder ssl: Can't find snapshot folder ssl
```
image

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (which adds functionality to the supervisor)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Additional information

- This PR fixes or closes issue: fixes #2391
- This PR is related to issue:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [x] Local tests pass. **Your PR cannot be merged unless tests pass**
- [x] There is no commented out code in this PR.
- [ ] I have followed the [development checklist][dev-checklist]
- [ ] The code has been formatted using Black (`black --fast supervisor tests`)
- [ ] Tests have been added to verify that the new code works.

If API endpoints of add-on configuration are added/changed:

- [ ] Documentation added/updated for [developers.home-assistant.io][docs-repository]

[dev-checklist]: https://developers.home-assistant.io/docs/en/development_checklist.html
[docs-repository]: https://github.com/home-assistant/developers.home-assistant

### CODE REVIEW

**Review by pvizeli — DISMISSED** [review]

**Review by pvizeli — COMMENTED** [review]
Now we lose our logs :(

**Comment by pvizeli** [comment]
We need a function like raise_and_log(....)

**Review by pvizeli — COMMENTED** [review]
We should not change the style out of the blue. Let's keep forward with the log where the error comes and raise an exception to handle the error later. We can use a new format, after the job manager is done

**Comment by ludeeus** [comment]
What style?
No log is lost here?

**Pull request closed without merging**
