### PR TITLE
Fix writing options with no schema

### PR DESCRIPTION
**Pull request by ludeeus**
## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (which adds functionality to the supervisor)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [ ] Local tests pass. **Your PR cannot be merged unless tests pass**
- [ ] There is no commented out code in this PR.
- [ ] I have followed the [development checklist][dev-checklist]
- [ ] The code has been formatted using Black (`black --fast supervisor tests`)
- [ ] Tests have been added to verify that the new code works.

If API endpoints of add-on configuration are added/changed:

- [ ] Documentation added/updated for [developers.home-assistant.io][docs-repository]

[dev-checklist]: https://developers.home-assistant.io/docs/en/development_checklist.html
[docs-repository]: https://github.com/home-assistant/developers.home-assistant

### CODE REVIEW

**Review by pvizeli — CHANGES_REQUESTED** [review]
That is wrong. Is options/schema are disabled, we don't need to write one

**Comment by ludeeus** [comment]
If you have options, but no schema we still need this write.
Currently, it writes `{}` no matter how many options/config there is if `schema: false`

**Comment by pdecat** [comment]
Hi @ludeeus, did you intentionally close this PR?

IIUC, it would resolve the issue we are having with the frigate addon which has `schema` set to `false`:
https://github.com/blakeblackshear/frigate/issues/703#issuecomment-775115961

**Comment by ludeeus** [comment]
I did

**Pull request closed without merging**
