### PR TITLE
Fix for supervisor internet check that fails when the system time is incorrect

### LINKED ISSUE #4883: supervisor check_connectivity is broken
### Describe the issue you are experiencing

On a newly unboxed Home Assistant Green there is no battery, so it boots up in April 2023.

The supervisor check of networking availability is performed here:
https://github.com/home-assistant/supervisor/blob/9c82ce4103b3e533a551f267f9c9b9799c73f476/supervisor/supervisor.py#L268

by this code:

    async def check_connectivity(self):
        """Check the connection."""
        timeout = aiohttp.ClientTimeout(total=10)
        try:
            await self.sys_websession.head(
                "https://checkonline.home-assistant.io/online.txt", timeout=timeout
            )
        except (ClientError, TimeoutError):
            self.connectivity = False
        else:
            self.connectivity = True

This controls the supervisor_internet flag as reported by ha's network info.

The brokenness derives from the fact that the SSL certificate for checkonline.home-assistant.io is only valid starting on May 16 2023:

```
 % curl --verbose --head https://checkonline.home-assistant.io/online.txt
*   Trying 104.26.4.238:443...
* Connected to checkonline.home-assistant.io (104.26.4.238) port 443
* ALPN: curl offers h2,http/1.1
* (304) (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* (304) (IN), TLS handshake, Server hello (2):
* (304) (IN), TLS handshake, Unknown (8):
* (304) (IN), TLS handshake, Certificate (11):
* (304) (IN), TLS handshake, CERT verify (15):
* (304) (IN), TLS handshake, Finished (20):
* (304) (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / AEAD-CHACHA20-POLY1305-SHA256
* ALPN: server accepted h2
* Server certificate:
*  subject: C=US; ST=California; L=San Francisco; O=Cloudflare, Inc.; CN=sni.cloudflaressl.com
*  start date: **May 16 00:00:00 2023 GMT**
*  expire date: May 15 23:59:59 2024 GMT
*  subjectAltName: host "checkonline.home-assistant.io" matched cert's "*.home-assistant.io"
*  issuer: C=US; O=Cloudflare, Inc.; CN=Cloudflare Inc ECC CA-3
*  SSL certificate verify ok.
* using HTTP/2
[...]

```

With this setup a newly unboxed Home Assistant Green will never work. You only get the screen with a bunch of logs, with surprisingly little information or control. Not be best user experience.

The workaround is to hook it up to a tv, find a USB keyboard (do they still even exist?), figure out that typing "login" will take you to the underlying Linux, and setting a date, and then rebooting.

This will then bring the supervisor_internet to true, and the system will finally boot up to the onboarding screen.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

1.
2.
3.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
24-02-09 01:12:04 DEBUG (MainThread) [supervisor.bus] Fire event 'supervisor_job_end' with 'ccec15716f2b423091f715298e2e5512'
24-02-09 01:12:04 INFO (MainThread) [supervisor.homeassistant.core] Wait until Home Assistant is ready
24-02-09 01:12:14 DEBUG (MainThread) [supervisor.api.middleware.security] Passthrough /supervisor/ping
24-02-09 01:12:16 ERROR (MainThread) [supervisor.homeassistant.api] Can't update Home Assistant access token!
24-02-09 01:12:16 DEBUG (MainThread) [supervisor.api.middleware.security] /homeassistant/options access from Home Assistant
24-02-09 01:12:25 DEBUG (MainThread) [supervisor.api.middleware.security] /supervisor/options access from Home Assistant
24-02-09 01:12:25 ERROR (MainThread) [supervisor.homeassistant.api] Can't update Home Assistant access token!
24-02-09 01:12:25 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state running
24-02-09 01:12:25 DEBUG (MainThread) [supervisor.hardware.monitor] Hardware monitor: add - Device('/sys/class/bluetooth')
24-02-09 01:12:25 DEBUG (MainThread) [supervisor.hardware.monitor] Hardware monitor: add - Device('/sys/module/bluetooth')
24-02-09 01:12:25 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
24-02-09 01:12:26 DEBUG (MainThread) [supervisor.api.middleware.security] /info access from Home Assistant
24-02-09 01:12:26 DEBUG (MainThread) [supervisor.api.middleware.security] /host/info access from Home Assistant
24-02-09 01:12:26 DEBUG (MainThread) [supervisor.api.middleware.security] /store access from Home Assistant
24-02-09 01:12:26 DEBUG (MainThread) [supervisor.api.middleware.security] /core/info access from Home Assistant
24-02-09 01:12:26 DEBUG (MainThread) [supervisor.api.middleware.security] /supervisor/info access from Home Assistant
24-02-09 01:12:26 DEBUG (MainThread) [supervisor.api.middleware.security] /os/info access from Home Assistant
24-02-09 01:12:26 DEBUG (MainThread) [supervisor.api.middleware.security] /ingress/panels access from Home Assistant
24-02-09 01:12:26 DEBUG (MainThread) [supervisor.api.middleware.security] /resolution/info access from Home Assistant
24-02-09 01:12:26 DEBUG (MainThread) [supervisor.api.middleware.security] /resolution/issue/affe3ee0480f4740a706e9729704c239/suggestions access from Home Assistant
24-02-09 01:12:26 DEBUG (MainThread) [supervisor.api.middleware.security] /info access from Home Assistant
24-02-09 01:12:26 DEBUG (MainThread) [supervisor.api.middleware.security] /core/info access from Home Assistant
24-02-09 01:12:26 DEBUG (MainThread) [supervisor.api.middleware.security] /supervisor/info access from Home Assistant
24-02-09 01:12:26 DEBUG (MainThread) [supervisor.api.middleware.security] /os/info access from Home Assistant
24-02-09 01:12:29 DEBUG (MainThread) [supervisor.api.middleware.security] /discovery access from Home Assistant
24-02-09 01:12:31 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
24-02-09 01:12:31 INFO (MainThread) [supervisor.homeassistant.core] Home Assistant Core state changed to RUNNING
24-02-09 01:12:31 INFO (MainThread) [supervisor.homeassistant.core] Detect a running Home Assistant instance
24-02-09 01:12:31 DEBUG (MainThread) [supervisor.bus] Fire event 'supervisor_job_end' with 'a629a2d36d854848abb2eb87bd16dfc2'
24-02-09 01:12:31 DEBUG (MainThread) [supervisor.bus] Fire event 'supervisor_job_start' with '78374e7706e34665870eee460c35fc4f'
24-02-09 01:12:31 INFO (SyncWorker_2) [supervisor.docker.manager] Cleanup images: ['ghcr.io/home-assistant/green-homeassistant:landingpage']
24-02-09 01:12:31 DEBUG (MainThread) [supervisor.bus] Fire event 'supervisor_job_end' with '78374e7706e34665870eee460c35fc4f'
24-02-09 01:12:31 DEBUG (MainThread) [supervisor.bus] Fire event 'supervisor_job_end' with '52f88e988b984390b8e3346dfc63c09a'
24-02-09 01:12:32 DEBUG (MainThread) [supervisor.homeassistant.websocket] Sending: {'type': <WSType.SUPERVISOR_EVENT: 'supervisor/event'>, 'data': {'event': <WSEvent.JOB: 'job'>, 'data': {'name': 'home_assistant_core_start', 'reference': None, 'uuid': 'a629a2d36d854848abb2eb87bd16dfc2', 'progress': 0, 'stage': None, 'done': True, 'parent_id': '52f88e988b984390b8e3346dfc63c09a', 'errors': []}}, 'id': 1}
24-02-09 01:12:32 DEBUG (MainThread) [supervisor.homeassistant.websocket] Sending: {'type': <WSType.SUPERVISOR_EVENT: 'supervisor/event'>, 'data': {'event': <WSEvent.JOB: 'job'>, 'data': {'name': 'docker_interface_cleanup', 'reference': 'homeassistant', 'uuid': '78374e7706e34665870eee460c35fc4f', 'progress': 0, 'stage': None, 'done': False, 'parent_id': '52f88e988b984390b8e3346dfc63c09a', 'errors': []}}, 'id': 2}
24-02-09 01:12:32 DEBUG (MainThread) [supervisor.homeassistant.websocket] Sending: {'type': <WSType.SUPERVISOR_EVENT: 'supervisor/event'>, 'data': {'event': <WSEvent.JOB: 'job'>, 'data': {'name': 'docker_interface_cleanup', 'reference': 'homeassistant', 'uuid': '78374e7706e34665870eee460c35fc4f', 'progress': 0, 'stage': None, 'done': True, 'parent_id': '52f88e988b984390b8e3346dfc63c09a', 'errors': []}}, 'id': 3}
24-02-09 01:12:32 DEBUG (MainThread) [supervisor.homeassistant.websocket] Sending: {'type': <WSType.SUPERVISOR_EVENT: 'supervisor/event'>, 'data': {'event': <WSEvent.JOB: 'job'>, 'data': {'name': 'home_assistant_core_install', 'reference': None, 'uuid': '52f88e988b984390b8e3346dfc63c09a', 'progress': 0, 'stage': None, 'done': True, 'parent_id': None, 'errors': []}}, 'id': 4}
24-02-09 01:12:34 DEBUG (MainThread) [supervisor.homeassistant.websocket] Received: WSMessage(type=<WSMsgType.TEXT: 1>, data='{"id":1,"type":"result","success":true,"result":null}', extra='')
24-02-09 01:12:34 DEBUG (MainThread) [supervisor.homeassistant.websocket] Received: WSMessage(type=<WSMsgType.TEXT: 1>, data='{"id":2,"type":"result","success":true,"result":null}', extra='')
24-02-09 01:12:34 DEBUG (MainThread) [supervisor.homeassistant.websocket] Received: WSMessage(type=<WSMsgType.TEXT: 1>, data='{"id":3,"type":"result","success":true,"result":null}', extra='')
24-02-09 01:12:34 DEBUG (MainThread) [supervisor.homeassistant.websocket] Received: WSMessage(type=<WSMsgType.TEXT: 1>, data='{"id":4,"type":"result","success":true,"result":null}', extra='')
24-02-09 01:13:18 DEBUG (MainThread) [supervisor.api.middleware.security] Passthrough /supervisor/ping
24-02-09 01:15:37 DEBUG (MainThread) [supervisor.api.middleware.security] /supervisor/options access from Home Assistant
24-02-09 01:15:37 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state running
24-02-09 01:15:38 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
24-02-09 01:15:51 DEBUG (MainThread) [supervisor.api.middleware.security] /supervisor/options access from Home Assistant
24-02-09 01:15:51 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state running
24-02-09 01:15:51 DEBUG (MainThread) [supervisor.utils.dbus] D-Bus call - io.hass.os.set_diagnostics on /io/hass/os
24-02-09 01:15:51 DEBUG (MainThread) [supervisor.utils.dbus] Property change for io.hass.os-/io/hass/os: ['Diagnostics'] changed & [] invalidated
24-02-09 01:15:52 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
24-02-09 01:15:57 DEBUG (MainThread) [supervisor.hardware.monitor] Hardware monitor: add - Device('/sys/module/bnep')
```

## System Information

version | core-2024.2.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.1
os_name | Linux
os_version | 6.1.59
arch | aarch64
timezone | Europe/Rome
config_dir | /config

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.1
-- | --
update_channel | stable
supervisor_version | supervisor-2024.01.1
agent_version | 1.6.0
docker_version | 24.0.6
disk_total | 28.0 GB
disk_used | 4.2 GB
healthy | true
supported | true
board | green
supervisor_api | ok
version_api | ok
installed_addons | 

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 0
mode | auto-gen

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | February 9, 2024 at 12:12 AM
-- | --
current_recorder_run | February 9, 2024 at 1:12 AM
estimated_db_size | 0.17 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

### Supervisor diagnostics

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by duncanwilcox**
## Proposed change

1) On a newly unboxed Home Assistant Green there is no battery, so it boots up in April 2023.
2) The supervisor_internet flag is set by loading https://checkonline.home-assistant.io/online.txt
3) The SSL certificate for checkonline.home-assistant.io currently is valid starting from May 16 2023

This ensures the check will fail, essentially bricking any system that doesn't have the correct time set.

The suggested change is to check http instead of https. The URL content is the same. I can't really think of any security implication.

## Type of change

- [ ] Dependency upgrade
- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (which adds functionality to the supervisor)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Additional information

- This PR fixes or closes issue: fixes #4883
- This PR is related to issue:
- Link to documentation pull request:
- Link to cli pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] Local tests pass. **Your PR cannot be merged unless tests pass**
- [ ] There is no commented out code in this PR.
- [ ] I have followed the [development checklist][dev-checklist]
- [ ] The code has been formatted using Ruff (`ruff format supervisor tests`)
- [ ] Tests have been added to verify that the new code works.

If API endpoints of add-on configuration are added/changed:

- [ ] Documentation added/updated for [developers.home-assistant.io][docs-repository]

[dev-checklist]: https://developers.home-assistant.io/docs/en/development_checklist.html
[docs-repository]: https://github.com/home-assistant/developers.home-assistant

### CODE REVIEW

**Comment by pvizeli** [comment]
Yeah, is also how NM handle it

**Comment by agners** [comment]
The Home Assistant OS tries to use NTP to synchronize time at startup. However, if that doesn't succeed (e.g. because no NTP server is provided by DHCP/we can't reach the fallback NTP from Cloudflare), the system will continue boot.

> With this setup a newly unboxed Home Assistant Green will never work. You only get the screen with a bunch of logs, with surprisingly little information or control. Not be best user experience.

With the above in mind, I don't really agree with the "never" word :sweat_smile: 

Do you happen to know why in your case the NTP time sync doesn't work? We do have these reports every now and then, but I really wonder if blocking NTP is that common or if there is another bug somewhere.

Also, we do have a "poor man NTP" based on HTTP built-in Supervisor, see https://github.com/home-assistant/supervisor/blob/2024.01.1/supervisor/core.py#L396-L403. Now I wonder why did that fail? :thinking: There was an error in Supervisor, not falling back to non-SSL correctly, but that should be fixed with https://github.com/home-assistant/supervisor/pull/4751.

**Comment by agners** [comment]
Ok, judging from the OS version in the linked issue your Green was pre-installed with HAOS 11.1, which has been released in October 26, 2023. So your Supervisor pre-installed had https://github.com/home-assistant/supervisor/pull/4751 not yet applied (this was part of [Supervisor 2023.12.0](https://github.com/home-assistant/supervisor/releases/tag/2023.12.0)). So effectively, your issue is fixed with #4751 already.

There was also a debate in the past weather it is a good idea to use http/port 80 for the connectivity check in NetworkManager, see https://github.com/home-assistant/operating-system/issues/1686. In that case the time was fine but port 80 was blocked, which caused even more trouble.

**Comment by duncanwilcox** [comment]
Well I know for sure that my particular HA Green was on for days and never started with the built-in OS and even with the recovery/reset procedure.

As far as I can tell providing NTP via DHCP isn't very common, or my DSL router doesn't provide it, but NTP isn't blocked and works fine (`sntp time.cloudflare.com` on my Mac works fine, same network).

I figure your reconstruction of the version that came with my HA Green is correct. Perhaps the reset image on the [Home Assistant Green reset page](https://green.home-assistant.io/guides/reset/) will need a similar fix.

I'm surprised anybody would block port 80 and not also block port 443. In the same vein as the commenter in [#1686](https://github.com/home-assistant/operating-system/issues/1686) I think it is surprising that this check would be necessary or appropriate, and while it's an architectural hard question, it's a hard question worth asking, because it leads to bricking devices.

**Comment by agners** [comment]
> As far as I can tell providing NTP via DHCP isn't very common, or my DSL router doesn't provide it, but NTP isn't blocked and works fine (sntp time.cloudflare.com on my Mac works fine, same network).

Yeah true, providing NTP via DHCP is not that common. I've seen ISP doing it when they block NTP on their end, which kinda make sense.

But the fact that NTP works fine now *really* makes we wonder why Home Assistant OS failed to set the time then! Can you maybe check `systemd-timesyncd` logs on your unit using the following command on the terminal:

```
journalctl --unit systemd-timesyncd.service
```

> I'm surprised anybody would block port 80 and not also block port 443. In the same vein as the commenter in https://github.com/home-assistant/operating-system/issues/1686 I think it is surprising that this check would be necessary or appropriate, and while it's an architectural hard question, it's a hard question worth asking, because it leads to bricking devices.

So your point is that no online check should be performed? I think I've outlined the reason a bit in the linked issue, but I guess the main point here is to have a single point to know if connectivity in general is up or down. It makes diagnosing issues easier, rather than inferring errors from various sources (external services like Docker, which actually really cause hard to interpret errors in the face of network connectivity issues) and (Supervisor) internal connection attempts.

**Comment by duncanwilcox** [comment]
Yes I think it's problematic to make assumptions about something generic as "internet" being up. To paraphrase from the other issue conversation, there are millions of linux installs that don't make any global internet check.

In a security conscious org (or person's home) you might have no internet al all. In China you only have some parts of the internet. With some firewalls, or a pihole, you might only have some ports. Partial availability might also be in the time domain, now it works, later it doesn't. It follows that you're still going to want to be checking for errors in any code that uses online resources, so why a global check?

Maybe you don't think much of the issues that are cropping up, but I'd say for a wider adoption of HA the global internet check needs to go.

You can ask for time in the web UI, if NTP doesn't work. Worst case is the user won't be able to update. But maybe the whole point of someone moving away from the Hue was to not expose their home automation to the internet, and they don't want the online thing.

My system was most definitely booted up with a 2023-04-04 date, and since you mentioned the fix to account for that was released in October 2023, clearly my preinstalled HA Green hat sat in the box for at least 4 months. I would say that it's better to remove the issue than to run after this specific thing.

Sorry I haven't found the time so far to configure remote access to run the journalctl.

**Comment by agners** [comment]
> Yes I think it's problematic to make assumptions about something generic as "internet" being up. To paraphrase from the other issue conversation, there are millions of linux installs that don't make any global internet check.

From what I know, Ubuntu as well as Fedora use NetworkManager, which has a global Internet check by default. :man_shrugging: 

That said, I am not sure what the global connectivity check of NetworkManager is typically used for on these desktop distributions.

The Internet connectivity check has been introduced with #2225. The aim seems to have been to prevent issues cropping up when there is no internet. I can image that if someone plug-in a cable a bit late, certain commands (e.g. add-on store fetch) or functions (e.g. version check) might fail, and the retry/recover might not been handled well.

I am not against removing the connectivity check. However, there was a reason it got introduced, and it presumably fixed problems. So any PR which removes the connectivity check would at least provide some testing evidence that such corner cases are (now) handled well, and the system overall behaves well when there is no connectivity and recovers on restored connectivity.

**Pull request closed without merging**
