### PR TITLE
Use technology neutral "auto"  instead of "dhcp" for autoconfiguration

### PR DESCRIPTION
**Pull request by agners**
IPv6 is often run with SLAAC which does not use a DHCP server but still
does automatic address configuration. Follow wording of NetworkManager
and use "auto" instead.

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (which adds functionality to the supervisor)
- [x] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] Local tests pass. **Your PR cannot be merged unless tests pass**
- [ ] There is no commented out code in this PR.
- [ ] I have followed the [development checklist][dev-checklist]
- [ ] The code has been formatted using Black (`black --fast supervisor tests`)
- [ ] Tests have been added to verify that the new code works.

If API endpoints of add-on configuration are added/changed:

- [ ] Documentation added/updated for [developers.home-assistant.io][docs-repository]

[dev-checklist]: https://developers.home-assistant.io/docs/en/development_checklist.html
[docs-repository]: https://github.com/home-assistant/developers.home-assistant

### CODE REVIEW

**Comment by ludeeus** [comment]
If we do this, we should just rip out our mapping and just use `NMInterfaceMethod`

**Review by pvizeli — COMMENTED** [review]
Looks good. You need fix all tests + update documentation + cli

> If we do this, we should just rip out our mapping and just use NMInterfaceMethod

This would remove our wanted abstraction between that interfaces

**Comment by ludeeus** [comment]
> This would remove our wanted abstraction between that interfaces

Correct, but with this, we are halfway between two types, which is weird.
If we still want our mapper, `STATIC` should become `MANUAL` as well

**Review by pvizeli — APPROVED** [review]
Fine to merge if docs & cli is ready

**Comment by agners** [comment]
> Correct, but with this, we are halfway between two types, which is weird.
Well the types just happen to have very similar values, but we use clearly different types. I think abstracting from NetworkManager does make sense in case we want to switch to something else in the future...

As for `static` or `manual`, either way is fine for me, but `dhcp` is really misleading/wrong in IPv6 context where DHCPv6 is not used (which is most often the case).

**Comment by agners** [comment]
@pvizeli 

- docs: https://github.com/home-assistant/supervisor/pull/2241 
- cli: https://github.com/home-assistant/cli/pull/260

**Pull request merged**
