### PR TITLE
Fix dev instructions

### LINKED ISSUE #2414: dev instructions in README don't work
### Describe the issue

Follow the developer instructions in the README and get an error in one of the steps (setting channel=dev).

Ignoring the error and proceeding with the developer instructions will allow you to use your supervisor image and test it, however the logs will report that the system verification failed and the system will fall back to the latest stable version on the next supervisor restart.

### Steps to reproduce

1. Obtain ssh root access to your ha instance on port 22222
2. Run `ha supervisor options --channel=dev` as stated in the README

```
ha > ha supervisor options --channel=dev
Error: unknown flag: --channel
Usage:
  ha core [command]

Aliases:
  core, homeassistant, home-assistant, ha

Examples:

  ha core check
  ha core restart
  ha core update
        ha core update --version 0.97.2

Available Commands:
  check       Validates your Home Assistant Core configuration
  info        Provides information about Home Assistant Core
  logs        View the log output of Home Assistant Core
  options     Allow to set options on Home Assistant Core instance
  rebuild     Rebuild the Home Assistant Core instance
  restart     Restarts the Home Assistant Core
  start       Manually start Home Assistant Core
  stats       Provides system usage stats of Home Assistant Core
  stop        Manually stop Home Assistant Core
  update      Updates the Home Assistant Core

Flags:
  -h, --help   help for core

Global Flags:
      --api-token string   Home Assistant Supervisor API token
      --config string      Optional config file (default is $HOME/.homeassistant.yaml)
      --endpoint string    Endpoint for Home Assistant Supervisor (default is 'supervisor')
      --log-level string   Log level (defaults to Warn)
      --no-progress        Disable the progress spinner
      --raw-json           Output raw JSON from the API

Use "ha core [command] --help" for more information about a command.

FATA[0000] Error while executing rootCmd: unknown flag: --channel
```

### Enviroment details

- **Operating System:**: Home Assistant OS 5.10
- **Supervisor version:**: 2020.12.7
- **Home Assistant version**: 2021.1.1

### Supervisor logs

<details>
<summary>Supervisor logs</summary>

```
21-01-10 02:48:07 INFO (MainThread) [supervisor.host] Host information reload completed
21-01-10 03:00:02 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING
21-01-10 03:00:02 INFO (MainThread) [supervisor.resolution.check] System checks complete
21-01-10 03:00:45 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
21-01-10 03:15:36 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING
21-01-10 03:15:36 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/beta.json
21-01-10 03:15:36 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete

```

</details>

### System Information

<details>
<summary>System Information</summary>

```
ha > ha info
The use of 'ha' is deprecated, please use 'core' instead!
arch: aarch64
audio_input: None
audio_output: None
boot: true
image: homeassistant/raspberrypi4-64-homeassistant
ip_address: 172.30.32.1
last_version: 2021.1.1
machine: raspberrypi4-64
port: 8123
ssl: false
update_available: false
version: 2021.1.1
version_latest: 2021.1.1
wait_boot: 600
watchdog: true

```

</details>

### PR DESCRIPTION
**Pull request by zeehio**
Closes #2414

## Proposed change

Minor issue in the instructions.

(The ha tool could give better help pages, it could have been easier to find out a solution)

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (which adds functionality to the supervisor)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [x ] Code quality improvements to existing code or addition of tests

## Additional information

- This PR fixes or closes issue: fixes #2414 
- This PR is related to issue:
- Link to documentation pull request:

## Checklist

- [x ] The code change is tested and works locally.
- [ x] Local tests pass. **Your PR cannot be merged unless tests pass**
- [x ] There is no commented out code in this PR.
- [x ] I have followed the [development checklist][dev-checklist]
- [ ] The code has been formatted using Black (`black --fast supervisor tests`)
- [ ] Tests have been added to verify that the new code works.

If API endpoints of add-on configuration are added/changed:

- [ ] Documentation added/updated for [developers.home-assistant.io][docs-repository]

[dev-checklist]: https://developers.home-assistant.io/docs/en/development_checklist.html
[docs-repository]: https://github.com/home-assistant/developers.home-assistant

### CODE REVIEW

**Comment by pvizeli** [comment]
They are now completely wrong (not because of this PR). Maybe we should just pin and leaf on devcontainer

**Comment by ludeeus** [comment]
I wonder if we should move the entire thing to https://developers.home-assistant.io/docs/supervisor/developing instead.

**Comment by ludeeus** [comment]
Using `=` works.
image

**Comment by zeehio** [comment]
At least part of my confusion comes because I was running `ha supervisor options --channel=dev` within the `ha>` shell instead of running it from a bash shell.

Even if I built my supervisor two weeks ago to test something I already forgot the exact steps. I should have written them down because I have a PR that I want to test again 😅!

I also found that setting the dev channel pulled some updates to some containers (e.g. multicast related). I'm not sure if that is expected or not, or its consequences when I want to go back to stable.

**Comment by ludeeus** [comment]
This is all expected, when you are directly connected to HAOS, you would skip the  `ha` prefix.
The  `dev` channel applies to everything, core/supervisor/plugins/OS
stable <https://version.home-assistant.io/stable.json>
dev <https://version.home-assistant.io/dev.json> 

This should only be done on a test installation, but if you want to revert back to stable, I suggest changing the channel back to `stable`, and then running `ha su repair` (again, if you are directly connected to HAOS you would skip the `ha` prefix)

**Comment by pvizeli** [comment]
Fix: https://github.com/home-assistant/supervisor/pull/2425

**Pull request closed without merging**
