### PR TITLE
Use aiohttp-fast-url-dispatcher to avoid linear searching to route urls

### PR DESCRIPTION
**Pull request by balloob**
This is a non-fork version of https://github.com/home-assistant/supervisor/pull/4683

---

The default `UrlDispatcher` implementation does a linear search every which can have a significant [TimeComplexity](https://wiki.python.org/moin/TimeComplexity) when dispatching urls when there are a lot of routes. `FastUrlDispatcher` keeps an index of the urls which allows for fast dispatch.

This solution was original implemented in core as
https://github.com/home-assistant/core/blob/241e8560e99da4cbd3c9f763d77cfbd8badb1c66/homeassistant/components/http/__init__.py#L592

It is now in a PyPI package so it can be reused in other projects until aiohttp 3.10 which will solve the problem via https://github.com/aio-libs/aiohttp/pull/7829

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (which adds functionality to the supervisor)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue:
- Link to documentation pull request:
- Link to cli pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] Local tests pass. **Your PR cannot be merged unless tests pass**
- [ ] There is no commented out code in this PR.
- [ ] I have followed the [development checklist][dev-checklist]
- [ ] The code has been formatted using Black (`black --fast supervisor tests`)
- [ ] Tests have been added to verify that the new code works.

If API endpoints of add-on configuration are added/changed:

- [ ] Documentation added/updated for [developers.home-assistant.io][docs-repository]

[dev-checklist]: https://developers.home-assistant.io/docs/en/development_checklist.html
[docs-repository]: https://github.com/home-assistant/developers.home-assistant

### CODE REVIEW

**Comment by frenck** [comment]
This PR should not be merged until we have finished the current cycle.

**Review by bdraco — APPROVED** [review]

**Comment by bdraco** [comment]
I was holding on this because I thought there was a problem, but it was with an external addon and happens on main as well so it turned out to be a red herring

**Review by mdegat01 — APPROVED** [review]
Not much to review but I see all the tests passed. Supervisor's API is pretty thoroughly unit tested at this point so this seems good to me then. Thanks @bdraco 👍

**Comment by bdraco** [comment]
Thanks

**Pull request merged**
