### PR TITLE
Create issue+suggestion when no recent backup

### PR DESCRIPTION
**Pull request by mdegat01**
## Proposed change

Currently the free space check also suggests making a full backup when there are none. This is rather out of place. Instead make a backups check that creates an issue+suggestion to make a backup when there are no full backups within the last 30 days. The 30 days threshold is configurable via the API.

This seems more useful. And it should be easier to migrate to the new repairs system since we always have an issue+suggestion together instead of just a suggestion.

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (which adds functionality to the supervisor)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue:
- Link to documentation pull request: https://github.com/home-assistant/developers.home-assistant/pull/1442
- Link to cli pull request: https://github.com/home-assistant/cli/pull/361

## Checklist

- [x] The code change is tested and works locally.
- [x] Local tests pass. **Your PR cannot be merged unless tests pass**
- [x] There is no commented out code in this PR.
- [x] I have followed the [development checklist][dev-checklist]
- [x] The code has been formatted using Black (`black --fast supervisor tests`)
- [x] Tests have been added to verify that the new code works.

If API endpoints of add-on configuration are added/changed:

- [ ] Documentation added/updated for [developers.home-assistant.io][docs-repository]

[dev-checklist]: https://developers.home-assistant.io/docs/en/development_checklist.html
[docs-repository]: https://github.com/home-assistant/developers.home-assistant

### CODE REVIEW

**Comment by frenck** [comment]
> Add an option for automatically taking full backups when last full backup is older then x days

That should be an automation/blueprint or something? This seems to be out of place towards the responsibilities of the Supervisor.

**Comment by mdegat01** [comment]
I guess I was thinking supervisor checks all sorts of things to see if your system is healthy or not and fixes them itself when possible. Not having a recent backup seemed like an issue. I can certainly remove the `auto_backup` option and just inform users when they probably should take a backup. But one more option to automate it seemed like a low cost and high value addition.

**Comment by frenck** [comment]
> Not having a recent backup seemed like an issue. 

I can think of way more things the Supervisor could "automate", IMHO we should not do that, as we automate in a different place.

>  I can certainly remove the auto_backup option and just inform users when they probably should take a backup.

I dunno if that is an issue, it could be an active decision.

**Review by pvizeli — APPROVED** [review]

**Comment by mdegat01** [comment]
@pvizeli I forget when exactly you reviewed and approved but to be clear you're good with this as right? It no longer automatically manages backups it simply suggests making one when there is no current one.

**Review by pvizeli — APPROVED** [review]

**Pull request merged**
