### PR TITLE
Add argument to reboot in fire-and-forget mode

### PR DESCRIPTION
**Pull request by agners**
If a reboot is triggered through the HA frontend, we cannot really
send back success information as the HA server is being shutdown during
that processes. In fact, the TCP connection delays shutdown of the core.
Allow to trigger the reboot without waiting for a result.

This allows to prevent an open TCP connection between the frontend and
the HA server. Currently the aiohttp server disconnects after 10s in any
case (and we could shorten that time as well), but rather than shorten
the delay further, just not wait for the operation seems the porper fix.

See also: https://github.com/home-assistant/core/pull/45033

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (which adds functionality to the supervisor)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [x] Local tests pass. **Your PR cannot be merged unless tests pass**
- [ ] There is no commented out code in this PR.
- [x] I have followed the [development checklist][dev-checklist]
- [ ] The code has been formatted using Black (`black --fast supervisor tests`)
- [ ] Tests have been added to verify that the new code works.

If API endpoints of add-on configuration are added/changed:

- [x] Documentation added/updated for [developers.home-assistant.io][docs-repository]: https://github.com/home-assistant/developers.home-assistant/pull/775

[dev-checklist]: https://developers.home-assistant.io/docs/en/development_checklist.html
[docs-repository]: https://github.com/home-assistant/developers.home-assistant

### CODE REVIEW

**Comment by agners** [comment]
First I was thinking to *not* wait by default. But when running from CLI it does make sense to report back as we would see if D-Bus errors or similar would happen.

**Comment by pvizeli** [comment]
I think that needs to be on the frontend which causes the issue because it's not only the host reboot even.

**Comment by agners** [comment]
Maybe I understand that wrong, but from what I understand the frontend does a POST request via API to the Supervisor, and the Supervisor. The supervisor starts to do operations and _does not_ complete the POST until HA is shutdown. And HA does not shutdown because the frontend is still waiting for that POST to complete.

Afaik, we can't make a "POST but don't wait for answer" on the frontend...

**Comment by agners** [comment]
Hm, I see, the hassio component in HA core can actually create a post request to the supervisor as a task and not wait for it just like I did here. Since the HA core is what the frontend invokes, and the problem is HA core's aiohttp server doesn't like that the connection stays open, I agree we should fix this in HA core instead here. Closing.

**Pull request closed without merging**
