### PR TITLE
Add backup and restore to CI

### PR DESCRIPTION
**Pull request by ludeeus**
## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (which adds functionality to the supervisor)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [x] Code quality improvements to existing code or addition of tests

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue:
- Link to documentation pull request:
- Link to cli pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] Local tests pass. **Your PR cannot be merged unless tests pass**
- [ ] There is no commented out code in this PR.
- [ ] I have followed the [development checklist][dev-checklist]
- [ ] The code has been formatted using Black (`black --fast supervisor tests`)
- [ ] Tests have been added to verify that the new code works.

If API endpoints of add-on configuration are added/changed:

- [ ] Documentation added/updated for [developers.home-assistant.io][docs-repository]

[dev-checklist]: https://developers.home-assistant.io/docs/en/development_checklist.html
[docs-repository]: https://github.com/home-assistant/developers.home-assistant

### CODE REVIEW

**Comment by ludeeus** [comment]
Because of https://github.com/home-assistant/supervisor/pull/3507 and https://github.com/home-assistant/supervisor/pull/3508 the CI is expected to fail

**Comment by sermayoral** [comment]
@ludeeus Wonderful!! Thanks for adding backup and restore to CI 🎉

**Comment by mdegat01** [comment]
@ludeeus I rebased it after merging the other two so it should pass now

**Comment by mdegat01** [comment]
Thanks @ludeeus 👍

**Pull request merged**
