### PR TITLE
Fix validation for "deeply" nested addon config

### LINKED ISSUE #2872: Addon schema parser - limited recursion.
### Describe the issue you are experiencing

Options schema for addons is limited to a recursion level of 2 seemingly as a result of this section utilising voluptuous:

[supervisor/addons/validate.py](https://github.com/home-assistant/supervisor/blob/2021.04.3/supervisor/addons/validate.py#L283-L299)
```python
        vol.Optional(ATTR_SCHEMA, default={}): vol.Any(
            vol.Schema(
                {
                    str: vol.Any(
                        SCHEMA_ELEMENT,
                        [
                            vol.Any(
                                SCHEMA_ELEMENT,
                                {str: vol.Any(SCHEMA_ELEMENT, [SCHEMA_ELEMENT])},
                            )
                        ],
                        vol.Schema({str: vol.Any(SCHEMA_ELEMENT, [SCHEMA_ELEMENT])}),
                    )
                }
            ),
            False,
        ),
```

This appears to be overcome when utilising voluptuous' Self feature for recursion as exampled in their docs. 

```python
        vol.Optional(ATTR_SCHEMA, default={}): vol.Any(
            vol.Schema(
                {
                    str: vol.Any(
                        SCHEMA_ELEMENT,
                        vol.Schema({str: vol.Any(SCHEMA_ELEMENT, [SCHEMA_ELEMENT], vol.Self)}),
                        [vol.Any(SCHEMA_ELEMENT, vol.Self)}],
                    )
                }
            ),
            False,
        ),
```

Unfortunately whilst that solves that issue, but it then causes issue with [supervisor/addons/options.py](https://github.com/home-assistant/supervisor/blob/2021.04.3/supervisor/addons/options.py#L298)

### What is the used version of the Supervisor?

supervisor-2021.04.3

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### What is the version of your installed operating system?

5.13

### What version of Home Assistant Core is installed?

core-2021.5.2

### Steps to reproduce the issue

1. Configure any addon config.json to have >2 levels of nesting, e.g
```json
{
   "name": "Cloudflare Tunnel",
   "version": "dev",
   "slug": "cloudflare-tunnel",
   "description": "Cloudflare tunnel add-on",
   "url": "<snip>",
   "init": false,
   "arch": [
      "aarch64",
      "amd64",
      "armhf",
      "armv7",
      "i386"
   ],
   "options": {
      "tunnels": [],
      "options": {
         "no-autoupdate": true
      }
   },
   "schema": {
      "tunnels": [
         {
            "enabled": "bool",
            "credentials": {
               "AccountTag": "str",
               "TunnelSecret": "str",
               "TunnelID": "str",
               "TunnelName": "str"
            },
            "ingress":[
           {
                 "hostname": "str?",
                 "service": "str?",
                 "path": "str?"
           }
        ],
            "options": {
               "loglevel": "list(trace|debug|info|warn|error|fatal|panic)?",
               "transport-loglevel": "list(trace|debug|info|warn|error|fatal|panic)?",
               "no-autoupdate": "bool?",
               "no-tls-verify": "bool?"
            }
         }
      ],
      "options": {
         "loglevel": "list(trace|debug|info|warn|error|fatal|panic)?",
         "transport-loglevel": "list(trace|debug|info|warn|error|fatal|panic)?",
         "no-autoupdate": "bool?",
         "no-tls-verify": "bool?"
      }
   }
}
```
2. reload from addon store
3. check supervisor logs

### Anything in the Supervisor logs that might be useful for us?

```txt
Logs (without updating supervisor/addons/validate.py):

21-05-12 00:58:43 WARNING (MainThread) [supervisor.store.data] Can't read /data/addons/local/cloudflare-tunnel/config.json: expected string or buffer @ data['schema']['tunnels'][0]['ingress'][0]. Got {'hostname': 'str?', 'service': 'str?', 'path': 'str?'}
expected string or buffer for dictionary value @ data['schema']['tunnels'][0]['credentials']. Got {'AccountTag': 'str', 'TunnelSecret': 'str', 'TunnelID': 'str', 'TunnelName': 'str'}
expected string or buffer for dictionary value @ data['schema']['tunnels'][0]['tunnel-options']. Got {'loglevel': 'list(trace|debug|info|warn|error|fatal|panic)?', 'transport-loglevel': 'list(trace|debug|info|warn|error|fatal|panic)?', 'no-autoupdate': 'bool?', 'no-tls-verify': 'bool?'}

Logs (with updating supervisor/addons/validate.py):
21-05-12 02:21:55 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/aiohttp.py", line 123, in sentry_app_handle
    reraise(*_capture_exception(hub))
  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/_compat.py", line 54, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/aiohttp.py", line 113, in sentry_app_handle
    response = await old_handle(self, request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/supervisor/supervisor/api/security.py", line 135, in system_validation
    return await handler(request)
  File "/usr/src/supervisor/supervisor/api/security.py", line 197, in token_validation
    return await handler(request)
  File "/usr/src/supervisor/supervisor/api/utils.py", line 65, in wrap_api
    answer = await method(api, *args, **kwargs)
  File "/usr/src/supervisor/supervisor/api/addons.py", line 226, in info
    ATTR_SCHEMA: addon.schema_ui,
  File "/usr/src/supervisor/supervisor/addons/model.py", line 552, in schema_ui
    return UiOptions(self.coresys)(raw_schema)
  File "/usr/src/supervisor/supervisor/addons/options.py", line 273, in __call__
    self._nested_ui_list(ui_schema, value, key)
  File "/usr/src/supervisor/supervisor/addons/options.py", line 375, in _nested_ui_list
    self._nested_ui_dict(ui_schema, element, key, multiple=True)
  File "/usr/src/supervisor/supervisor/addons/options.py", line 400, in _nested_ui_dict
    self._single_ui_option(nested_schema, c_value, c_key)
  File "/usr/src/supervisor/supervisor/addons/options.py", line 298, in _single_ui_option
    match = RE_SCHEMA_ELEMENT.match(value)
TypeError: expected string or bytes-like object
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Wh1terat**
## Proposed change

This PR fixes "deeply"(>2)  nested options and their validation.

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (which adds functionality to the supervisor)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Additional information

- This PR fixes or closes issue: fixes #2872, #2560

## Checklist

- [x] The code change is tested and works locally.
- [x] Local tests pass. **Your PR cannot be merged unless tests pass**
- [x] There is no commented out code in this PR.
- [x] I have followed the [development checklist][dev-checklist]
- [x] The code has been formatted using Black (`black --fast supervisor tests`)
- [x] Tests have been added to verify that the new code works.

If API endpoints of add-on configuration are added/changed:

- [ ] Documentation added/updated for [developers.home-assistant.io][docs-repository]

[dev-checklist]: https://developers.home-assistant.io/docs/en/development_checklist.html
[docs-repository]: https://github.com/home-assistant/developers.home-assistant

### CODE REVIEW

**Comment by pvizeli** [comment]
please provide some examples

**Comment by Wh1terat** [comment]
@pvizeli As listed in #2872 

```json
{
   "name": "Cloudflare Tunnel",
   "version": "dev",
   "slug": "cloudflare-tunnel",
   "description": "Cloudflare tunnel add-on",
   "url": "<snip>",
   "init": false,
   "arch": [
      "aarch64",
      "amd64",
      "armhf",
      "armv7",
      "i386"
   ],
   "options": {
      "tunnels": [],
      "options": {
         "no-autoupdate": true
      }
   },
   "schema": {
      "tunnels": [
         {
            "enabled": "bool",
            "credentials": {
               "AccountTag": "str",
               "TunnelSecret": "str",
               "TunnelID": "str",
               "TunnelName": "str"
            },
            "ingress":[
	       {
                 "hostname": "str?",
                 "service": "str?",
                 "path": "str?"
	       }
	    ],
            "options": {
               "loglevel": "list(trace|debug|info|warn|error|fatal|panic)?",
               "transport-loglevel": "list(trace|debug|info|warn|error|fatal|panic)?",
               "no-autoupdate": "bool?",
               "no-tls-verify": "bool?"
            }
         }
      ],
      "options": {
         "loglevel": "list(trace|debug|info|warn|error|fatal|panic)?",
         "transport-loglevel": "list(trace|debug|info|warn|error|fatal|panic)?",
         "no-autoupdate": "bool?",
         "no-tls-verify": "bool?"
      }
   }
}
```

This could cause
```text
21-05-12 00:58:43 WARNING (MainThread) [supervisor.store.data] Can't read /data/addons/local/cloudflare-tunnel/config.json: expected string or buffer @ data['schema']['tunnels'][0]['ingress'][0]. Got {'hostname': 'str?', 'service': 'str?', 'path': 'str?'}
expected string or buffer for dictionary value @ data['schema']['tunnels'][0]['credentials']. Got {'AccountTag': 'str', 'TunnelSecret': 'str', 'TunnelID': 'str', 'TunnelName': 'str'}
expected string or buffer for dictionary value @ data['schema']['tunnels'][0]['tunnel-options']. Got {'loglevel': 'list(trace|debug|info|warn|error|fatal|panic)?', 'transport-loglevel': 'list(trace|debug|info|warn|error|fatal|panic)?', 'no-autoupdate': 'bool?', 'no-tls-verify': 'bool?'}
```

**Comment by Wh1terat** [comment]
Any additional comments?

I appreciate there is a PR to refactor configuration in general, but that will be a breaking change - this is not and would solve the current limitation.

Thanks.

**Comment by Wh1terat** [comment]
@pvizeli ?

**Comment by Wh1terat** [comment]
2 week bump.

Accept or Reject, don't just ignore hoping for the bot will close it down for you without having the decency to reply to people who've invested their own time into rectifying defects.

**Comment by pvizeli** [comment]
It makes no sense to forward with the old options/schema system which is deprecated with the new RFC. This request is solved with: https://github.com/home-assistant/supervisor/issues/2640

But I don't see that I can implement 2640 until Q4. Help is welcome.

**Comment by Wh1terat** [comment]
Definitely in favour of #2640 - it is a more elegant approach, but this is a non breaking change to provide improved functionality as a stop-gap measure until #2640 can be implemented.

#2640 is a breaking change and as you say, it could be another 6 months+ before it makes its way even into the dev channel.

That said, happy to assist where I can.

**Comment by pvizeli** [comment]
It's already almost everything in place to make an migration and add the feature without breaking change

**Comment by prestegaard** [comment]
Hi, is this moving somewhere?
I've been tracking this fix since May and have a project relying on the nesting levels to increase.
Do I need to go for another solution, or will this be approved and merged quite soon?
Thanks for this effort, would be a great improvement to have this :)

**Comment by pascalMN** [comment]
> Hi, is this moving somewhere?
> I've been tracking this fix since May and have a project relying on the nesting levels to increase.
> Do I need to go for another solution, or will this be approved and merged quite soon?
> Thanks for this effort, would be a great improvement to have this :)

Same here

**Comment by pvizeli** [comment]
I close the PR, the solution is described in that PR and on the RFC. To implement this is not on the roadmap for 2021 but I'm happy to see contributions with implement the new solution, described on the RFC

**Pull request closed without merging**
