### PR TITLE
Addons can access systemd journal logs

### PR DESCRIPTION
**Pull request by mdegat01**
## Proposed change

I have added a boolean addon configuration option of `systemd-journal`. When set to true `/var/logs/journal` is mapped into the addon container as read-only. This gives the add-on the ability to read from the system journal and see all logs from across all addons.

I would like to add this capability to enable the creation of logging service addons like Grafana's [Loki](https://grafana.com/oss/loki/). This tool is a log aggregator that then lets you easily visualize, explore, analyze and monitor your logs in other tools such as [Grafana](https://grafana.com/grafana/). I'm using Loki as an example because it happens that the community add-ons repository already has a Grafana add-on which I believe is very popular. There also happens to be a [community guide](https://community.home-assistant.io/t/setting-up-grafana-loki-promtail/259059) around Loki and Promtail but its not one that anyone with supervisor would be able to follow (or should follow since it involves directly creating docker containers outside of supervisor). Loki is also just an example, there is a whole class of services which provide tooling and services around logs.

In order for this to work though, you need access to the logs. By default there are very few logs add-ons can access, basically just the home assistant log file. Nearly all other add-ons and all the supervisor components log to stdout by default which gets recorded to the system journal, all completely inaccessible to addons at the moment. And even the the home assistant log you can get to is very tough to parse since it is pure text, the `json` logs in the journal for homeassistant are much more useful.

There are a number of feature requests around improvements to logs that addons could now help to fill with this access. Besides [the one I submitted](https://community.home-assistant.io/t/use-an-external-logging-service-in-ha-os/289321) here's some other examples:
- https://community.home-assistant.io/t/make-system-log-persistant/288443
- https://community.home-assistant.io/t/feature-request-greater-log-persistance/206400
- https://community.home-assistant.io/t/longer-persistent-logs-for-add-ons/92371
- https://community.home-assistant.io/t/monitoring-the-logs-after-crash/121575
- https://community.home-assistant.io/t/backing-up-home-assistant-log-file-on-restarts/171574
- https://community.home-assistant.io/t/log-managemenet-rotate-and-backup/164982

Really just a sampling. A search for `persistent logs` or `backup logs` shows a lot of people wondering how they can do better log management. The ability to hand them to a service dedicated to this task would be a huge improvement.

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (which adds functionality to the supervisor)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue: https://community.home-assistant.io/t/use-an-external-logging-service-in-ha-os/289321
- Link to documentation pull request: https://github.com/home-assistant/developers.home-assistant/pull/851

## Checklist

- [x] The code change is tested and works locally.
- [x] Local tests pass. **Your PR cannot be merged unless tests pass**
- [x] There is no commented out code in this PR.
- [x] I have followed the [development checklist][dev-checklist]
- [x] The code has been formatted using Black (`black --fast supervisor tests`)
- [x] Tests have been added to verify that the new code works.

If API endpoints of add-on configuration are added/changed:

- [x] Documentation added/updated for [developers.home-assistant.io][docs-repository]

[dev-checklist]: https://developers.home-assistant.io/docs/en/development_checklist.html
[docs-repository]: https://github.com/home-assistant/developers.home-assistant

### CODE REVIEW

**Comment by mdegat01** [comment]
I know I have to add tests and doc and will do so. But before I do I wanted to open this as draft to get thoughts from the maintainers. Wanted to make sure people agreed with the concept and proposal before investing more time getting it to done.

**Comment by mdegat01** [comment]
Also just an FYI I did do a manual test of this functionality. I couldn't test this in devcontainers of vscode since it seems that setup runs in an unsupported environment and one of the things it is missing is `journald` logging. So I tested this in a local HassOS install in virtualbox by manually pointing `/usr/src` at my branch in the `hassio_supervisor` container and issuing a `docker restart`. [Here's the config](https://paste.ubuntu.com/p/M2pHkYXWJJ/) for my super simple testcase addon that can be dropped in a folder in `/addons` to try it out.

**Review by pvizeli — COMMENTED** [review]
call it just journald

**Comment by mdegat01** [comment]
Ok I changed the option to `journald`, added tests for the new capability and opened a doc PR to list the new option. Given that the dev checklist is complete figured I would take it out of draft.

I'm not sure what's going on with the check labels failure. It seems to be looking for the `cla-signed`  label but that's been added already. I can't change labels on PRs so hoping someone can help me with that one.

**Review by pvizeli — APPROVED** [review]

**Pull request merged**
